version: '3.3'
services:
  web:
    build: .
    image: viktorchek/hosting:v0.1.0
    ports:
      - "80:25000"
    environment:
     - DB_USER=db_user
     - DB_PASSWORD=db_password
     - DB_NAME=db_name
  postgres:
    image: postgres
    environment:
     - POSTGRES_USER=db_user
     - POSTGRES_PASSWORD=db_password
     - POSTGRES_DB=db_name

